# Numpy problems


### 1. Write a Python program to convert a list of numeric value into a one-dimensional
    NumPy array.
    Expected Output:
    Original List: [12.23, 13.32, 100, 36.32]
    One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [1]:
import numpy as np

In [19]:
original_list = [12.23,234,13.32,100,324,23.56]

#numpy.set_printoptions if you want to control the output being printed by decimals
numpy_array = np.array(original_list)

print("Original List:", original_list)
print("One-dimensional numpy array:", numpy_array)


Original List: [12.23, 234, 13.32, 100, 324, 23.56]
One-dimensional numpy array: [ 12.23 234.    13.32 100.   324.    23.56]


### 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [22]:
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### 3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [31]:
null_vector = np.zeros(9)#.reshape(3,3)
null_vector[5] = 11

print(null_vector)


[ 0.  0.  0.  0.  0. 11.  0.  0.  0.]


### 4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [32]:
original_array = np.arange(12, 38)

print("Original array:", original_array)
print("Reversed array:", original_array[::-1])


Original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


### 5. Write a Python program to create a 2d array with 1 on the border and 0 inside.


In [40]:
rows, cols = 5, 5

array = np.zeros((rows, cols), dtype=int)

array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:,-1] = 1

print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### 6. Write a Python program to add a border (filled with 0's) around an existing array.


In [43]:
original_array = np.ones((3, 3), dtype=int)

bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

print("Original array:")
print(original_array)
print("\nArray with border:")
print(bordered_array)


Original array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Array with border:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


### 7.Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:

In [7]:
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1


print(checkerboard)


[[0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]]


### 8.Write a Python program to convert a list and tuple into arrays.

In [8]:

list_to_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("List to array:")
print(list_to_array)

tuple_to_array = np.array([(8, 4, 6), (1, 2, 3)])
print("Tuple to array:")
print(tuple_to_array)


List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
 [1 2 3]]


### 9.Write a Python program to append values to the end of an array.

In [9]:
array = np.array([10, 20, 30])
print("Original array:")
print(array)

array = np.append(array, [40, 50, 60, 70, 80, 90])
print("After append values to the end of the array:")
print(array)


Original array:
[10 20 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


### 10.Write a Python program to find the real and imaginary parts of an array of complex numbers.

In [10]:
complex_array = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
print("Original array:")
print(complex_array)

real_part = np.real(complex_array)
print("Real part of the array:")
print(real_part)

imaginary_part = np.imag(complex_array)
print("Imaginary part of the array:")
print(imaginary_part)


Original array:
[1.        +0.j         0.70710678+0.70710678j]
Real part of the array:
[1.         0.70710678]
Imaginary part of the array:
[0.         0.70710678]


### 11.Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [14]:
array = np.array([1, 2, 3,3443222])
print("Size of the array:", array.size)
print("Length of one array element in bytes:", array.itemsize)
print("Total bytes consumed by the elements of the array:", array.nbytes)


Size of the array: 4
Length of one array element in bytes: 4
Total bytes consumed by the elements of the array: 16


### 12.Find the common values between arrays

In [21]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40,20])

common_values = np.intersect1d(array1, array2)
print("Common values between two arrays:")
print(common_values)


Common values between two arrays:
[10 20 40]


### 13.Find the set difference of two arrays

In [18]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

set_difference = np.setdiff1d(array2,array1)
print("Set difference between two arrays:")
print(set_difference)


Set difference between two arrays:
[30 50 70 90]


### 14. Find the Set Exclusive-Or of Two Arrays

In [22]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

exclusive_or = np.setxor1d(array1, array2)
print("unique values that are in only one of the input arrays:")
print(exclusive_or)


Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


### 15.Compare Two Arrays

In [31]:
a = np.array([1, 2])
b = np.array([4, 5])
c = np.array([10,10])

print("a > b")
print(a > b)

print("a >= b")
print(a >= b)


print("a < b")
print(a < b)

print("a <= b")
print(a <= b)


a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


### 15.(2)Save a NumPy Array to a Text File

In [32]:
array = np.array([1, 2, 3, 4, 5])

np.savetxt('array.txt', array, fmt='%d')


### 16.Create a Contiguous Flattened Array

In [33]:
array = np.array([[10, 20, 30], [20, 40, 50]])

flattened_array = array.flatten()
print("New flattened array:")
print(flattened_array)


New flattened array:
[10 20 30 20 40 50]


### 17.Change the Data Type of an Array

In [ ]:
x = np.array([[2, 4, 6], [6, 8, 10]], dtype=np.int32)
print("Data type of the array x is:", x.dtype)

x = x.astype(np.float64)
print("New Type:", x.dtype)
print(x)


### 18.Create a 3-D Array with Ones on a Diagonal and Zeros Elsewhere

In [39]:
array = np.eye(3)
print(array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 19. Create an Array that Looks Like the Given Array
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [42]:
# array = np.array([[0, 0, 0], [1, 0, 0], [1, 1, 0], [1, 1, 1]])
# print(array)

array = np.zeros((4, 3), dtype=int)

for i in range(1, 4):
    array[i, :i] = 1

print(array)



[[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


### 20. Concatinate Two 2-dimensional arrays

In [47]:
array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])

result = np.concatenate((array1, array2), axis=0)
print("Concatenated array:")
print(result)


Concatenated array:
[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


### 21. Make an Array Immutable (Read-Only)

In [57]:
x = np.array([1, 2, 3])

x.flags.writeable = False

try:
    x[0] = 40
    print(x)
except ValueError as e:
    print("Error:", e)


Error: assignment destination is read-only


### 22.Create an Array of Shape (3, 4), Multiply Every Element by 3, and Display the New Array

In [54]:
array = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print("Original array elements:")
print(array)

new_array = array * 3
print("New array elements:")
print(new_array)


Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


### 23.Convert a NumPy Array into a Python List Structure

In [55]:
array = np.array([[0, 1], [2, 3], [4, 5]])
print("Original array elements:")
print(array)

array_to_list = array.tolist()
print("Array to list:")
print(array_to_list)

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


### 24.Write a Python program to convert a NumPy array into Python list structure.

In [56]:
array = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 
                  0.35399976, 0.99469633, 0.0694458, 0.54711478])

array_to_list = array.tolist()
print("Array to list:")
print(array_to_list)

np.set_printoptions(precision=3)
print("Array values with precision 3:")
print(array)


Array to list:
[0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478]
Array values with precision 3:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


### 25. Write a Python program to suppresses the use of scientific notation for small numbers in numpy array.

In [60]:
array = np.array([1.6e-10, 1.6e+00, 1.2e+03, 2.35e-01])

np.set_printoptions(suppress=True, precision=3)
print("Array values with precision 3:")
print(array)


Array values with precision 3:
[   0.       1.6   1200.       0.235]


### 26.Add extra column to numpy array

In [61]:
array = np.array([[10, 20, 30], [40, 50, 60]])

new_column = np.array([[100], [200]])
result = np.hstack((array, new_column))
print("Array after adding a new column:")
print(result)


Array after adding a new column:
[[ 10  20  30 100]
 [ 40  50  60 200]]


### 27.Remove Specific Elements in a NumPy Array

In [62]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
indices_to_remove = [0, 3, 4]

new_array = np.delete(array, indices_to_remove)
print("Array after deleting specific elements:")
print(new_array)


Array after deleting specific elements:
[ 20  30  60  70  80  90 100]
